# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make <- function(i, j) {
    .Call(`_xptrpkgs_make`, i, j)
}

release <- function(p) {
    invisible(.Call(`_xptrpkgs_release`, p))
}

